import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Lora } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair',
});

const lora = Lora({ 
  subsets: ['latin'],
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${lora.variable} antialiased`}>
      <head>
        <title>Frk-bering.dk - Clairvoyant vejledning og businesskonsulent</title>
        <meta name="description" content="Få indsigt i din indre visdom og opdage din fulde potentiale med clairvoyance, healing og businesskonsultation. Line Bering hjælper dig med at leve et mere bevidst og fyldestgørende liv." />
      </head>
      <body>{children}</body>
    </html>
  );
}
